### PR TITLE
add density

### PR DESCRIPTION
**Pull request by ericthewry**
Here's some moderately interesting information about density that confirms some obvious facts.

Post when you've read so we can merge.

@rwoll @MelanieWu

### CODE REVIEW

**Comment by rwoll** [comment]
Thanks @ericthewry for running this metrics. As discussed, I think this formally confirms why the complexity of running temporal shortest path algs are not nearly as slow as their upper-bound complexities suggest. Based on this and some of the other papers linked into the reading repo, the algs should terminate in a reasonable amount of time given our data-set. (See page 731 of [http://www.vldb.org/pvldb/vol7/p721-wu.pdf](http://www.vldb.org/pvldb/vol7/p721-wu.pdf) for runtimes of some small samples on various real-world data-sets -- including `dblp`.) If we are interested only in the number of edges in the path (instead of the fully enumerated path) that should make computations simpler as well.

**Comment by ericthewry** [comment]
Cool. That should work out. I say we just go ahead and try it. Something
worth noting is that most treatments of DBLP seem to assume edge
permanence, creating a slightly different model of coauthorship than the
one we're interested in.

**Comment by rwoll** [comment]
If we are calculating paths based on accumulating windows I think it makes sense for an edge to have permanence, otherwise we would be looking at a series of static graphs -- unless we introduce a time-dependent edge weight system.

**Comment by ericthewry** [comment]
The two different models fundamentally change the semantics of what "shortest path" means. Shortest path with edge permanence allows traversal across all collaborations that have happened historically, where defining some notion of time-limited edge allows for traversal across *contemporary* collaborations. Both are valuable, it just depends on what we're interested in.

In terms of a time-dependent weighting system; I think that's valuable -- but computes a different metric. The paper you cited identifies this difference by making a distinction between fastest path and shortest path.

"
(3) fastest path (i.e., the path by which one goes from x to
y with the minimum elapsed time); and (4) shortest path (i.e., the
path that is shortest from x to y in terms of overall traversal time
needed on the edges).
Note that a shortest path may not necessarily be a fastest path
(e.g., in a traffic network the shortest path from x to y may have a
lot of traffic lights, while a highway is longer but is the fastest way
to go from x to y).
"

**Pull request merged**
